const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const XLSX = require('xlsx');

const app = express();
const PORT = 5000;

// ── Middleware ──────────────────────────────────────────────────────────────
app.use(cors({
  origin: ['http://localhost:5173', 'http://127.0.0.1:5173'],
  credentials: true,
}));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true }));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// ── Multer ──────────────────────────────────────────────────────────────────
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    const dir = path.join(__dirname, 'uploads');
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    cb(null, dir);
  },
  filename: (req, file, cb) => cb(null, Date.now() + '-' + file.originalname),
});
const upload = multer({ storage });

// ── In-memory store ─────────────────────────────────────────────────────────
let stats = {
  totalLogins: 0,
  deptWiseLogins: {
    'Computer Science': 0,
    'Information Technology': 0,
    'Electronics & Communication': 0,
    'Electrical & Electronics': 0,
    'Mechanical Engineering': 0,
  },
  studentUsage: [],
};
let preBookings = [];
let feedbacks = [];

// ── Load real e-books from ebooks.json (generated by scripts/fetch-books.js) ─
function loadFeaturedEbooks() {
  const ebooksPath = path.join(__dirname, 'ebooks.json');
  if (!fs.existsSync(ebooksPath)) {
    console.warn('⚠️  ebooks.json not found. Run: node scripts/fetch-books.js');
    return [];
  }
  try {
    const data = JSON.parse(fs.readFileSync(ebooksPath, 'utf-8'));
    console.log(`\n📚  Real e-books loaded from ebooks.json:`);
    data.forEach(b => console.log(`   ${b.cover}  ${b.title}  (${b.pages.length} pages)`));
    return data;
  } catch (err) {
    console.error('Error reading ebooks.json:', err.message);
    return [];
  }
}

// ── Load books from Excel ───────────────────────────────────────────────────
function loadBooksFromExcel() {
  try {
    const filePath = path.join(__dirname, '../BooksData(7).xlsx');
    if (!fs.existsSync(filePath)) {
      console.log('Excel file not found – skipping Excel books.');
      return [];
    }
    const workbook = XLSX.readFile(filePath);
    const sheet = workbook.Sheets[workbook.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(sheet, { header: 1 });
    const dataRows = rows.slice(4);

    const loaded = dataRows.map((row, index) => {
      if (!row[3]) return null;
      const title = row[3];
      const author = row[5] || 'Unknown';
      const category = row[9] || 'General';
      const pageCount = row[15] || 0;
      return {
        id: `excel-${index + 1}`,
        title, category,
        pages: [
          `Title: ${title}\nAuthor: ${author}\nCategory: ${category}\n\n(Cover Page)`,
          `About this Book:\nThis is a digital reference for "${title}".\nPublished by: ${row[11] || 'N/A'}\nYear: ${row[16] || 'N/A'}`,
          `Preview:\nThis book "${title}" is part of the ${category} collection.\nPhysical edition contains ${pageCount} pages.\n\nPlease visit the library for the complete physical copy.`,
          `To borrow this book:\n\n1. Click the "Pre-Book" button on the book card.\n2. Admin will be notified.\n3. Collect the book within 24 hours from the library counter.`,
        ],
        ratings: [],
        isEbook: false,
      };
    }).filter(Boolean);

    console.log(`✅  Loaded ${loaded.length} books from Excel.`);
    return loaded;
  } catch (err) {
    console.error('Error loading Excel:', err.message);
    return [];
  }
}

// ── Assemble full book list ──────────────────────────────────────────────────
let books = [
  ...loadFeaturedEbooks(),
  ...loadBooksFromExcel(),
];

// ═══════════════════════════════════════════════════════════════════════════
//  ROUTES
// ═══════════════════════════════════════════════════════════════════════════

// ── Auth ─────────────────────────────────────────────────────────────────────
app.post('/api/login/student', (req, res) => {
  const { name, department, rollNo, year } = req.body;
  if (!name || !rollNo)
    return res.status(400).json({ success: false, message: 'Name and Roll Number are required.' });
  stats.totalLogins++;
  stats.deptWiseLogins[department] = (stats.deptWiseLogins[department] || 0) + 1;
  res.json({ success: true, user: { name, department, rollNo, year, loginTime: new Date() } });
});

app.post('/api/login/admin', (req, res) => {
  const { username, password } = req.body;
  if (username === '12345678' && password === 'sandhya')
    res.json({ success: true, role: 'admin' });
  else
    res.status(401).json({ success: false, message: 'Invalid credentials.' });
});

// ── Logout ───────────────────────────────────────────────────────────────────
app.post('/api/logout', (req, res) => {
  const { name, duration } = req.body;
  stats.studentUsage.push({ name, duration, date: new Date().toLocaleDateString() });
  res.json({ success: true });
});

// ── Pre-booking ───────────────────────────────────────────────────────────────
app.post('/api/prebook', (req, res) => {
  const { studentName, bookTitle } = req.body;
  preBookings.push({ studentName, bookTitle, time: new Date(), status: 'pending' });
  res.json({ success: true });
});
app.get('/api/admin/notifications', (req, res) => res.json(preBookings));

// ── Feedback ──────────────────────────────────────────────────────────────────
app.post('/api/feedback', (req, res) => {
  const { studentName, bookTitle, message, rating } = req.body;
  feedbacks.push({ studentName, bookTitle, message, rating: Number(rating), date: new Date() });
  const book = books.find(b => b.title === bookTitle);
  if (book) { if (!book.ratings) book.ratings = []; book.ratings.push(Number(rating)); }
  res.json({ success: true });
});
app.get('/api/admin/feedbacks', (req, res) => res.json(feedbacks));

// ── Stats ─────────────────────────────────────────────────────────────────────
app.get('/api/admin/stats', (req, res) => res.json(stats));

// ── Books: list (lightweight — no pages in list to keep response small) ───────
app.get('/api/books', (req, res) => {
  const list = books.map(b => ({
    id: b.id,
    title: b.title,
    author: b.author,
    category: b.category,
    cover: b.cover,
    isEbook: b.isEbook,
    ratings: b.ratings,
    pageCount: b.pages ? b.pages.length : 0,
  }));
  res.json(list);
});

// ── Helper: Fetch Dynamic Content from Wikipedia ────────────────────────────
async function fetchDynamicContent(title) {
  const https = require('https');
  const cleanTitle = title.replace(/\([^)]*\)/g, '').split(',')[0].trim();

  return new Promise((resolve) => {
    const url = `https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro=false&explaintext=true&titles=${encodeURIComponent(cleanTitle)}&format=json&redirects=1`;

    const req = https.get(url, { headers: { 'User-Agent': 'DigitalLibrary/1.0' } }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          const pages = json.query.pages;
          const wikiPage = pages[Object.keys(pages)[0]];

          if (!wikiPage.extract) {
            resolve(["We're sorry, but the full digital content for this book is currently being digitized. \n\nCheck back soon, or try reading one of our Featured E-Books!"]);
            return;
          }

          // Chunk the Wikipedia text into pages
          const text = wikiPage.extract;
          const chunks = [];
          const maxChar = 2000;
          for (let i = 0; i < text.length; i += maxChar) {
            chunks.push(text.slice(i, i + maxChar).trim());
          }
          resolve(chunks);
        } catch {
          resolve(["Content is currently unavailable for online reading."]);
        }
      });
    });
    req.on('error', () => resolve(["Connectivity issue. Could not fetch online content."]));
    req.setTimeout(5000, () => { req.destroy(); resolve(["Timeout fetching content."]); });
  });
}

// ── Books: get single book WITH pages (for reading) ───────────────────────────
app.get('/api/books/:id', async (req, res) => {
  const book = books.find(b => String(b.id) === String(req.params.id));
  if (!book) return res.status(404).json({ message: 'Book not found.' });

  // If book has no pages (normal book), fetch dynamically
  if (!book.pages || book.pages.length === 0) {
    const pages = await fetchDynamicContent(book.title);
    return res.json({ ...book, pages });
  }

  res.json(book);
});

// ── Download a book as .txt ───────────────────────────────────────────────────
app.get('/api/books/:id/download', async (req, res) => {
  const book = books.find(b => String(b.id) === String(req.params.id));
  if (!book) return res.status(404).json({ message: 'Book not found.' });

  let pages = book.pages;
  if (!pages || pages.length === 0) {
    pages = await fetchDynamicContent(book.title);
  }

  const sep = '\n\n' + '═'.repeat(72) + '\n\n';
  const header = `${book.title}\nby ${book.author || 'Unknown'}\n\n${'─'.repeat(72)}\n\n`;
  const content = header + pages.join(sep);
  const filename = book.title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_') + '.txt';

  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send(content);
});

// ── Add book ──────────────────────────────────────────────────────────────────
app.post('/api/books', upload.single('bookFile'), (req, res) => {
  const { title, category, pages } = req.body;
  const bookPages = pages
    ? pages.split('\n\n').filter(p => p.trim())
    : [`"${title}" — digital preview coming soon.`];

  const newBook = {
    id: `custom-${Date.now()}`,
    title, category,
    pages: bookPages,
    fileName: req.file ? req.file.filename : null,
    ratings: [],
    isEbook: false,
  };
  books.push(newBook);
  res.json({ ...newBook, pageCount: newBook.pages.length });
});

// ── Delete book ───────────────────────────────────────────────────────────────
app.delete('/api/books/:id', (req, res) => {
  const book = books.find(b => String(b.id) === String(req.params.id));
  if (book && book.fileName) {
    const fp = path.join(__dirname, 'uploads', book.fileName);
    if (fs.existsSync(fp)) fs.unlinkSync(fp);
  }
  books = books.filter(b => String(b.id) !== String(req.params.id));
  res.json({ success: true });
});

// ── Start ─────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  const ebooks = books.filter(b => b.isEbook);
  console.log(`\n🚀  Smart Library backend → http://localhost:${PORT}`);
  console.log(`📖  Featured e-books : ${ebooks.length}`);
  console.log(`📚  Total books      : ${books.length}\n`);
});
